"use client";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/components/auth/auth-provider";

type Profile = { display_name: string | null; avatar_url: string | null; preferred_currency: string };
export function ProfileSettings() {
  const { user, signOut } = useAuth();
  const [profile, setProfile] = useState<Profile>({ display_name: "", avatar_url: "", preferred_currency: "CAD" });
  const [notice, setNotice] = useState<string | null>(null), [deleting, setDeleting] = useState(false), [confirm, setConfirm] = useState(""), [signOutOpen, setSignOutOpen] = useState(false);
  useEffect(() => { if (user) void createClient().from("profiles").select("display_name,avatar_url,preferred_currency").single().then(({ data }) => data && setProfile(data)); }, [user]);
  async function save() { if (!user) return; const supabase = createClient(); const { error } = await supabase.from("profiles").upsert({ id: user.id, ...profile }); if (!error) await supabase.auth.updateUser({ data: { ...user.user_metadata, display_name: profile.display_name, avatar_url: profile.avatar_url, preferred_currency: profile.preferred_currency } }); setNotice(error?.message ?? "Profile saved."); }
  async function reset() { if (!user?.email) return; const { error } = await createClient().auth.resetPasswordForEmail(user.email, { redirectTo: `${window.location.origin}/auth/reset-password` }); setNotice(error?.message ?? "Password-reset instructions have been sent."); }
  async function remove() { const response = await fetch("/api/account", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ confirmation: confirm }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error ?? "Could not delete account."); window.location.assign("/auth/sign-in"); }
  return <div className="max-w-2xl space-y-6"><div><h1 className="text-3xl font-bold">Settings</h1><p className="mt-1 text-muted-foreground">Manage your profile and account security.</p></div>
    <section className="rounded-2xl border bg-card p-6"><h2 className="text-lg font-semibold">Profile</h2><p className="mt-1 text-sm text-muted-foreground">Your email is managed by your sign-in provider.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Email<input value={user?.email ?? ""} disabled className="mt-1.5 w-full rounded-xl border bg-muted px-3 py-2" /></label><label className="text-sm font-medium">Display name<input value={profile.display_name ?? ""} onChange={(e) => setProfile({ ...profile, display_name: e.target.value })} className="mt-1.5 w-full rounded-xl border bg-background px-3 py-2" /></label><label className="text-sm font-medium">Avatar URL<input type="url" value={profile.avatar_url ?? ""} onChange={(e) => setProfile({ ...profile, avatar_url: e.target.value })} className="mt-1.5 w-full rounded-xl border bg-background px-3 py-2" /></label><label className="text-sm font-medium">Reporting currency<select value={profile.preferred_currency} onChange={(e) => setProfile({ ...profile, preferred_currency: e.target.value })} className="mt-1.5 w-full rounded-xl border bg-background px-3 py-2">{["CAD","USD","EUR","GBP","AUD","JPY"].map((x) => <option key={x}>{x}</option>)}</select></label></div>{notice && <p className="mt-4 text-sm text-muted-foreground">{notice}</p>}<button onClick={() => void save()} className="mt-5 rounded-xl bg-primary px-4 py-2 font-medium text-primary-foreground">Save profile</button></section>
    <section className="rounded-2xl border bg-card p-6"><h2 className="text-lg font-semibold">Security</h2><div className="mt-4 flex gap-3"><button onClick={() => void reset()} className="rounded-xl border px-4 py-2 text-sm font-medium">Request password reset</button><button onClick={() => setSignOutOpen(true)} className="rounded-xl border px-4 py-2 text-sm font-medium">Sign out</button></div></section>
    <section className="rounded-2xl border border-destructive/30 bg-destructive/5 p-6"><h2 className="text-lg font-semibold text-destructive">Delete account</h2><p className="mt-1 text-sm text-muted-foreground">This permanently deletes your profile and financial data. This cannot be undone.</p>{deleting ? <><input value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder="Type DELETE" className="mt-4 w-full rounded-lg border bg-background px-3 py-2" /><div className="mt-3 flex gap-3"><button onClick={() => setDeleting(false)} className="rounded-lg border px-3 py-2">Cancel</button><button disabled={confirm !== "DELETE"} onClick={() => void remove()} className="rounded-lg bg-destructive px-3 py-2 text-destructive-foreground disabled:opacity-50">Permanently delete</button></div></> : <button onClick={() => setDeleting(true)} className="mt-4 rounded-xl bg-destructive px-4 py-2 text-sm font-medium text-destructive-foreground">Delete account</button>}</section>
    {signOutOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4"><div className="w-full max-w-sm rounded-2xl bg-card p-6"><h2 className="text-lg font-semibold">Sign out?</h2><p className="mt-2 text-sm text-muted-foreground">You’ll need to sign in again to access your finances.</p><div className="mt-6 flex justify-end gap-3"><button onClick={() => setSignOutOpen(false)} className="px-3 py-2">Cancel</button><button onClick={async () => { await signOut(); window.location.assign("/auth/sign-in"); }} className="rounded-lg bg-destructive px-3 py-2 text-destructive-foreground">Sign out</button></div></div></div>}
  </div>;
}
